name: "Actirepo Automation"
description: "Ejecuta actirepo para actualizar los ficheros README.md del repositorio de actividades"
inputs:
  branch:
    description: "Branch en el que se hará el push"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    # Instalar Chromium
    - name: Instalar Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    # Instalar el módulo desde el repositorio
    - name: Instalar el módulo Python
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/teuton-software/actirepo.git

    # Ejecutar el comando actirepo
    - name: Ejecutar comando actirepo
      run: actirepo --repository . --recursive --force

    # Hacer el push de los cambios
    - name: Hacer push de los cambios
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Automated changes by actirepo"
        git push origin ${{ inputs.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
