name: "Actirepo Automation"
description: "Ejecuta actirepo para actualizar los ficheros README.md del repositorio de actividades"
inputs:
  branch:
    description: "Branch en el que se hará el push"
    required: false
    default: "main"
  token:
    description: "Token de GitHub"
    required: true    

runs:
  using: "composite"
  steps:
    # Checkout del repositorio actual
    - name: Checkout del código
      uses: actions/checkout@v4

    # Instalar Chromium
    - name: Instalar Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
      shell: bash

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Instalar el módulo desde el repositorio
    - name: Instalar actirepo
      run: |
        pip install git+https://github.com/teuton-software/actirepo.git#egg=actirepo
      shell: bash

    # Ejecutar el comando actirepo
    - name: Ejecutar comando actirepo
      run: actirepo --repository . --recursive --force
      shell: bash

    # Hacer el push de los cambios
    - name: Hacer push de los cambios
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "Automated changes by actirepo"
        git push origin ${{ inputs.branch }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
