name: "Actirepo Automation"
description: "Ejecuta actirepo para actualizar los ficheros README.md del repositorio de actividades"
inputs:
  branch:
    description: "Branch en el que se hará el push"
    required: false
    default: "main"
  token:
    description: "Token de GitHub"
    required: true    

runs:
  using: "composite"
  steps:
    # Checkout del repositorio actual
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    # Instalar Google Chrome
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Instalar el módulo desde el repositorio
    - name: Instalar actirepo
      run: |
        pip install git+https://github.com/teuton-software/actirepo.git
      shell: bash

    # Ejecutar el comando actirepo
    - name: Ejecutar comando actirepo
      run: |
        actirepo --repository "${{ github.workspace }}" --readme --recursive --force
      shell: bash

    # Crear un pull request con los cambios
    - name: Crear un PR con los cambios
      run: |
        gh pr create -B ${{ inputs.branch }} -H ${{ inputs.branch }} --title 'READMEs generados por actirepo' --body 'Created by actirepo GitHub Action'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
