name: "actirepo automation"
description: "Ejecuta actirepo para actualizar los ficheros README.md del repositorio de actividades"
inputs:
  branch:
    description: "Branch sobre el que se va a trabajar"
    required: false
    default: "main"
  token:
    description: "Token de GitHub"
    required: true
  force:
    description: "Forzar la actualización de los ficheros README.md"
    required: false
    default: "--force"

runs:
  using: "composite"
  steps:
    # Checkout del repositorio actual
    - name: Checkout del código
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    # Instalar Google Chrome
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Instalar el módulo desde el repositorio
    - name: Instalar actirepo
      run: |
        pip install git+https://github.com/teuton-software/actirepo.git
      shell: bash

    # Ejecutar el comando actirepo
    - name: Ejecutar comando actirepo
      run: |
        actirepo --repository "${{ github.workspace }}" --readme --recursive ${{ inputs.force }}
      shell: bash

    # Commit de los cambios
    - name: Commit de los cambios
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        cd ${{ github.workspace }}
        git add .
        git commit -m "automated changes by actirepo"
        git push origin ${{ inputs.branch }}
      shell: bash
      env: 
        GITHUB_TOKEN: ${{ inputs.token }}
